engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "dist/**/*.js"

  exclude_paths:
   - "dist/coverage/**/*.js"
   - "dist/build/*.js"
   - "dist/lib/*.js"
   - "dist/components/**/*spec.js"

